version: "3.9"

services:
  # ───────────────────────────────────────────────
  # Vault 1 — Leader 후보
  # ───────────────────────────────────────────────
  vault1:
    image: hashicorp/vault:1.19.0          # ▶︎ 1.17+ 안정 버전
    hostname: vault1                       # ▶︎ 클러스터 내부 식별용
    container_name: vault1
    restart: unless-stopped
    cap_add:
      - IPC_LOCK                           # ▶︎ 메모리 잠금, 성능·보안↑
    volumes:
      - ./config/vault1.hcl:/vault/config/local.hcl:ro  # ▶︎ 설정 파일 마운트 (읽기전용)
      - ./volume/vault1/data:/vault/data                # ▶︎ Raft 스토리지
    networks:
      - vault-net
    ports:
      - "8201:8200"                        # ▶︎ 필요 시 포트 개방 (선택)

  # ───────────────────────────────────────────────
  # Vault 2 — Follower
  # ───────────────────────────────────────────────
  vault2:
    image: hashicorp/vault:1.19.0
    hostname: vault2
    container_name: vault2
    restart: unless-stopped
    cap_add: [ "IPC_LOCK" ]
    volumes:
      - ./config/vault2.hcl:/vault/config/local.hcl:ro
      - ./volume/vault2/data:/vault/data
    networks: [ vault-net ]
    ports:
      - "8202:8200"

  # ───────────────────────────────────────────────
  # Vault 3 — Follower
  # ───────────────────────────────────────────────
  vault3:
    image: hashicorp/vault:1.19.0
    hostname: vault3
    container_name: vault3
    restart: unless-stopped
    cap_add: [ "IPC_LOCK" ]
    volumes:
      - ./config/vault3.hcl:/vault/config/local.hcl:ro
      - ./volume/vault3/data:/vault/data
    networks: [ vault-net ]
    ports:
      - "8203:8200"

networks:
  vault-net:
    driver: bridge                         # ▶︎ 단일 호스트 기준. 멀티노드시 overlay 사용